AWSTemplateFormatVersion: 2010-09-09
Description: Your CloudFormation Template Description

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow HTTP access"
      VpcId: 'your-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'your-ami-id'
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      SubnetId: 'your-subnet-id'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt update
          sudo apt install -y apache2
          sudo systemctl enable apache2
          sudo systemctl start apache2
        Tags:
        - Key: Name
          Value: MyEC2InstanceName
